name: CMake

on: [ push ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Build artifact
        id: build
        with:
          arch: aarch64
          distro: ubuntu20.04
          githubToken: ${{ github.token }}
          setup: |
            mkdir -p "${PWD}/artifacts"

          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"

          env: |
            BUILD_TYPE: Release

          shell: /bin/bash

          install: |
            apt update -q -y
            apt install -q -y build-essential cmake qt5-default libqt5websockets-dev

          run: |
            cmake -E make_directory ${{github.workspace}}/build
            cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
            cmake --build . --config $BUILD_TYPE
            ctest -C $BUILD_TYPE
            cp erised /artifacts/erised
      - name: Upload the Artifacts
        uses: actions/upload-artifact@v2.2.2
        with:
          # Artifact name
          name: erised
          # A file, directory or wildcard pattern that describes what to upload
          path: artifacts/

