name: documentation

on:
  push:
    branches:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Fetch latest Docuowl release
          id: docuowl
          uses: pozetroninc/github-action-get-latest-release@v0.5.0
          with:
            owner: docuowl
            repo: docuowl
            exclude: prerelease, draft
        - name: Download Docuowl binaries
          run: |
            DOCUOWL_URL="https://github.com/docuowl/docuowl/releases/download/%s/docuowl_%s_Linux_x86_64.tar.gz"
            DOCUOWL_RELEASE=${{steps.docuowl.outputs.release}}
            DOCUOWL_VERSION=${DOCUOWL_RELEASE/v/}
            FORMATTED_URL=$(printf ${DOCUOWL_URL} ${DOCUOWL_RELEASE} ${DOCUOWL_VERSION})
            wget ${FORMATTED_URL} -O docuowl.tar.gz
            tar xf docuowl.tar.gz
            rm docuowl.tar.gz
