name: documentation

on:
  push:
    branches:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            ref: gh-pages
        - name: Fetch latest Docuowl release
          id: docuowl
          uses: pozetroninc/github-action-get-latest-release@v0.5.0
          with:
            owner: docuowl
            repo: docuowl
            exclude: prerelease, draft
        - name: Download Docuowl binaries
          run: |
            DOCUOWL_URL="https://github.com/docuowl/docuowl/releases/download/%s/docuowl_%s_Linux_x86_64.tar.gz"
            DOCUOWL_RELEASE=${{steps.docuowl.outputs.release}}
            DOCUOWL_VERSION=${DOCUOWL_RELEASE/v/}
            FORMATTED_URL=$(printf ${DOCUOWL_URL} ${DOCUOWL_RELEASE} ${DOCUOWL_VERSION})
            mkdir docuowl-release
            wget ${FORMATTED_URL} -O docuowl.tar.gz
            tar xf docuowl.tar.gz --directory docuowl-release
            rm docuowl.tar.gz
        - name: Build documentation
          run: |
            rm -rf docs
            ./docuowl-release/docuowl --input docs-src --output docs
        - name: Cleanup
          run: rm -rf ./docuowl-release
        - name: Push changes
          uses: EndBug/add-and-commit@v7.0.0
          with:
            message: "docs: autoupdate documentation"
