name: documentation

on:
  push:
    branches:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Fetch latest Docuowl release
          id: docuowl
          uses: pozetroninc/github-action-get-latest-release@v0.5.0
          with:
            owner: docuowl
            repo: docuowl
            exclude: prerelease, draft
        - name: Download Docuowl binaries
          run: echo ${{steps.docuowl.outputs.release}}
